# Generated by Django 5.2.6 on 2025-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_last_location_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(default='High-Risk', max_length=50)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('radius_km', models.FloatField()),
            ],
        ),
    ]
